{"timestamp":"2025-10-04T02:23:12.834982Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-04T02:23:12.835912Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/sql_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-04T02:23:12.909139Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.909566Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.910215Z","level":"info","event":"Current task name:get_data","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.910646Z","level":"info","event":"Dag name:process_employees","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.968027Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /apache/airflow/main/airflow-core/docs/tutorial/pipeline_example.csv (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f40cfa03650>: Failed to resolve 'raw.githubusercontent.com' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":252,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/sql_dag.py","lineno":54,"name":"get_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":677,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /apache/airflow/main/airflow-core/docs/tutorial/pipeline_example.csv (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f40cfa03650>: Failed to resolve 'raw.githubusercontent.com' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPSConnection object at 0x7f40cfa03650>: Failed to resolve 'raw.githubusercontent.com' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/python/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-04T02:23:12.972794Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.973090Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.973340Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): get_data>","logger":"task.stdout"}
{"timestamp":"2025-10-04T02:23:12.973550Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /apache/airflow/main/airflow-core/docs/tutorial/pipeline_example.csv (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f40cfa03650>: Failed to resolve 'raw.githubusercontent.com' ([Errno -2] Name or service not known)\"))","logger":"task.stdout"}
